# Generated by Django 5.1.7 on 2025-04-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_access_token_user_refresh_token'),
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='places.diningplace')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'blacklist_carousel',
                'unique_together': {('user_id', 'place_id')},
            },
        ),
        migrations.CreateModel(
            name='FavouriteCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='places.diningplace')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'favourite_carousel',
                'unique_together': {('user_id', 'place_id')},
            },
        ),
        migrations.CreateModel(
            name='ShownCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interested', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='places.diningplace')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shown_carousel',
                'unique_together': {('user_id', 'place_id')},
            },
        ),
    ]
